# [START runtime]
runtime: nodejs14
env: standard


# [END runtime]

# [START handlers]
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)$
    static_files: build/\1
    upload: build/(.*)
  - url: .*
    script: main.app
    secure: always